### PR TITLE
bug/xss

### PR DESCRIPTION
**Pull request by mauricesvay**
This PR improves how option UI is rendered:
* code should be cleaner, each option type has been moved to its own file
* security should be improved, in particular xss issues

Merging this PR will bump the project to 1.0.5.

### CODE REVIEW

**Comment by mauricesvay** [comment]
Needs rebase

**Comment by mauricesvay** [comment]
Rebased

**Comment by mauricesvay** [comment]
@kornifex when you have some time, it would be nice to have a review 🙏

**Review by kornifex — APPROVED** [review]
We should probably try to have a standard view which implements all the template stuff, but we can live with it for now!

**Pull request merged**
