### PR TITLE
Adds texture option

### PR DESCRIPTION
**Pull request by mauricesvay**
This PR add a new option type: `texture`.
This options allows users to change the texture of channels of a material.

### CODE REVIEW

**Review by Kuranes — APPROVED** [review]
Looks good. 
(no addition in the json schema, was already in it?)

**Comment by mauricesvay** [comment]
json schema is in separate PR. Will add it to the schema when the other PR is merged.

**Review by kornifex — APPROVED** [review]
:+1:

**Comment by cedricpinson** [comment]
@mauricesvay would be great to have the resource on skfb s3 ?
I am talking about this https://mauricesvay.s3.amazonaws.com/sketchfab/tmp/face-default.png

**Comment by pierreant-p** [comment]
Where is this deployed/used?
We could probably deploy it to https://apps.sketchfab.com/configurator-something-whatever, and the textures would be there as well?

**Comment by mauricesvay** [comment]
@pierreant-p at the moment this repo isn't deployed anywhere. `apps.sketchfab.com` sounds good.

**Comment by mauricesvay** [comment]
@cedricpinson I've removed the URL from example and docs. Should be good now.

**Pull request merged**
